site_name: Markatzeko Lengoaiak eta Informazioa Kudeatzeko Sistemak
site_description: Markatzeko Lengoaiak eta Informazioa Kudeatzeko Sistemak apunteak eta ariketak
site_url: https://martinezjone.github.io/lm_apunteak/

theme:
  name: material
  language: es

  logo: images/logo.png
  favicon: http://fptxurdinaga.eus/wp-content/uploads/2022/10/favicon-96x96-1.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#004c95"
      accent: "#e95f15"
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#004c95"
      accent: "#e95f15"
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: es
          default: true
          name: Español
          build: true
        - locale: eu
          name: Euskara
          build: true
          nav_translations:
            Inicio: Hasiera
            Introducción: Sarrera

nav:
  - Inicio: index.md
  - Introducción: 01-introduccion/index.md
  - HTML: 02-html/index.md
  - CSS: 03-css/index.md
  - XML: 04-xml/index.md
  - XSLT: 05-xslt/index.md
  - JavaScript: 06-javascript/index.md
  - CMS: 07-cms/index.md
